name: print-date-dir

on:
  push:
    branches:
      - main

jobs:
  print_date_dir:
    runs-on: ubuntu:latest
    steps:
      - name: Print date
        run: |
          date

      - name: Print directory
        run: |
          ls
